name: secure_wipe_app
description: Cross-platform UI for Secure Data Wiping Platform
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.6
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.7
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
